# Generated by Django 6.0.4 on 2026-05-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfusionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_products', models.ManyToManyField(blank=True, related_name='confusion_entries', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Confusion Entries',
            },
        ),
    ]
